FROM rust:1.87 AS builder

WORKDIR /app
COPY . .
RUN cargo build --release --bin movie-server

FROM debian:bullseye-slim
WORKDIR /app
COPY --from=builder /app/target/release/movie-server .
CMD ["./movie-server"]
