FROM rust:1.87 AS builder

WORKDIR /app
COPY . .
RUN cargo build --release --bin movie-client

FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/target/release/movie-client .

EXPOSE 5000

CMD ["./movie-client"]
