FROM rust:1.87 as builder

RUN apt-get update && apt-get install -y protobuf-compiler musl-tools pkg-config libssl-dev && \
    rustup target add x86_64-unknown-linux-musl

WORKDIR /app
COPY . .

RUN cargo build --release --target x86_64-unknown-linux-musl --bin movie-client

FROM alpine:3.20

WORKDIR /app
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/movie-client .

EXPOSE 5000
CMD ["./movie-client"]
