FROM rust:1.87 AS builder


RUN apt-get update && apt-get install -y protobuf-compiler pkg-config libssl-dev

WORKDIR /app
COPY . .

RUN cargo build --release --bin movie-client

FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/target/release/movie-client .

EXPOSE 5000

CMD ["./movie-client"]
