global:
  scrape_interval:     10s
  evaluation_interval: 10s


scrape_configs:
  - job_name: 'movie-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:5000']
        labels:
          application: 'movie-grpc-service'
  
  - job_name: "otel-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8889"]
