global:
  scrape_interval:     10s
  evaluation_interval: 10s


scrape_configs:
  - job_name: 'movie-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:5000']
        labels:
          application: 'movie_grpc_service'

