name: Build and push Rust binaries

on:
  push:
    branches: [main]
    tags:
      - v*
  pull_request:
    paths:
      - 'Dockerfile.*'
      - 'src/**'
      - 'Cargo.*'
      - '.github/workflows/rust.yml'

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - name: movie-client
            dockerfile: Dockerfile.client
          - name: movie-server
            dockerfile: Dockerfile.server

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/mamangrust/movie-grpc-tonic-axum/${{ matrix.target.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=${{ matrix.target.name }}
            org.opencontainers.image.description=Rust binary image for ${{ matrix.target.name }}
            org.opencontainers.image.source=https://github.com/movie-grpc-tonic-axum
            org.opencontainers.image.licenses=MIT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.target.dockerfile }}
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/mamangrust/movie-grpc-tonic-axum/${{ matrix.target.name }}:latest
          labels: ${{ steps.meta.outputs.labels }}
